### ISSUE TITLE
`Dispose()` does not work reliably when called during application shutdown

### ISSUE THREAD

**Issue by ssrmm** [hardcodet/wpf-notifyicon#122]
It looks like the implementation in #93 was not fully correct. I'm seeing the following problems related to calling `TaskbarIcon.Dispose()` explicitly during application shutdown:
1. Explicit dispose may deadlock itself with the one triggered by `TaskbarIcon`s `Application.Exit` handler.
2. Dispose may throw `TaskCanceledException` when called explicitly during application shutdown. Note that this second problem already happened before the mentioned PR as well.

Both of these only happen sporadically. Unfortunately I am neither able to reproduce them in a minimal example nor am I able to share the code of the actual application. So I've written down my observations below..

In my own code, I've now removed the explicit `TaskbarIcon.Dispose()` entirely, relying on the dispose from `Application.Exit`, and suppressing the dispose-releated analyzer warning instead. This works for me because application and tray icon lifetime are coupled in my case. But that may not be the case for other applications, so a general solution to the problem still makes sense I think.

## Deadlock
Here is a screenshot from Visual Studios Parallel Stacks view showing the problem. From what I can tell, the following happens:
1. A thread other than the UI-Thread calls `Application.Current.Dispatcher.BeginInvoke(() => Application.Current.Shutdown())` (or similar). This will queue the shutdown operation on the UI thread.
2. The same or yet another threads calls `TaskbarIcon.Dispose()`.
4. `TaskbarIcon.Dispose()` takes the lock in [TaskbarIcon.cs#L1105](https://github.com/hardcodet/wpf-notifyicon/blob/0a9d1a92914db8fb6b1cca1f073469644cd9bf3b/src/NotifyIconWpf/TaskbarIcon.cs#L1105)
5. `TaskbarIcon.Dispose()` queues the unsubscribe from `Application.Exit` on the dispatcher and waits until it finished executing (`Application.Current.Dispatcher.Invoke(() => Application.Current.Exit -= OnExit)`).
6. The dispatcher executes the `Application.Current.Shutdown()` from earlier on the UI thread and invokes `Application.Exit` handlers as part of that procedure
7. `TaskbarIcon.OnExit()` gets called and invokes `TaskbarIcon.Dispose()`.
8. The second `TaskbarIcon.Dispose()` call tries to acquire the lock which is currently held by the other thread that caused the first invocation.
9. The UI thread is blocked, will never get to the unsubscribe from `Application.Exit` and so the other thread will never return form the `Dispatcher.Invoke()` call.
![image](https://github.com/user-attachments/assets/9e989846-6697-44e1-9a7e-fe9e4013d691)

## `TaskCanceledException`
Here I don't really have any concrete information as to why this exception happens. My best guess is that the application shutdown has already progressed far enough that the application dispatcher is not functional anymore and cannot be called.
```
Exception Info: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Hardcodet.Wpf.TaskbarNotification.TaskbarIcon.Dispose(Boolean disposing) in D:\a\1\s\src\NotifyIconWpf\TaskbarIcon.cs:line 1113
   at Hardcodet.Wpf.TaskbarNotification.TaskbarIcon.Dispose() in D:\a\1\s\src\NotifyIconWpf\TaskbarIcon.cs:line 1074
```

**Comment by SunSerega** [comment]
Here is a MRE:
```
        public MainWindow()
        {
            InitializeComponent();

            var icon = new TaskbarIcon();

            Task.Run(icon.Dispose); // need to call from another thread so that Dispatcher.Invoke is not a no-op

            icon.Visibility = Visibility.Hidden;

        }
```
`icon.Dispose` takes a lock and then tries to call `Dispatcher.Invoke`, which waits on the main window thread to finish work:
```
                    // Dispose may be called by any thread, so we need to dispatch the event access to the correct thread.
                    Application.Current.Dispatcher.Invoke(() => Application.Current.Exit -= OnExit);
```
However, the main window thread cannot finish its work because of setting visibility to hidden calls `TaskbarIcon.RemoveTaskbarIcon`, which also tries to take the same lock.

Generally, calling the blocking `Dispatcher.Invoke` when a lock is taken is a bad idea.
A simple fix for this would be to call `Dispatcher.BeginInvoke` and wait for completion only after releasing the lock.
